#! perl

#:META:RESOURCE:%.cmd:string:the command to run the GUI filebrowser

=head1 NAME

open-filebrowser - open GUI filebrowser at selection

=head1 EXAMPLES

  URxvt.keysym.C-M-a: open-filebrowser:open

=head1 DESCRIPTION

This is a little extension that opens a GUI filebrowser (Thunar, Nautilus, etc.)
at the selection. It is aimed at being the converse of the "open terminal here"
in such applications. It can be triggered via a keyboard shortcut or with the
CTRL-rightclick menu (selection popup in urxvt language).

The command can can be set via a resource:

   URxvt.open-filebrowser.cmd: thunar
   URxvt.open-imageviewer.cmd: gthumb

=cut

sub openbrowser {
   my ($self) = @_;

   my $txt = $self->selection;

   my $cmd = $self->{open_filebrowser_cmd};

   $cmd = $cmd . " " . $txt;

   my $pid = $self->exec_async ($cmd);
}

sub openimageviewer {
   my ($self) = @_;

   my $txt = $self->selection;

   my $cmd = $self->{open_imageviewer_cmd};

   $cmd = $cmd . " " . $txt;

   my $pid = $self->exec_async ($cmd);
}

sub on_start {
   my ($self) = @_;

   $self->{open_filebrowser_cmd} = $self->x_resource ("%browser.cmd")
                           || "thunar ";

   $self->{open_imageviewer_cmd} = $self->x_resource ("viewer%.cmd")
                           || "gthumb ";

   push @{ $self->{term}{selection_popup_hook} }, sub {
      ("open filebrowser here" => sub { $self->openbrowser })
   };

   push @{ $self->{term}{selection_popup_hook} }, sub {
      ("open image viewer here" => sub { $self->openimageviewer })
   };

   ()
}

sub on_user_command {
   my ($self, $cmd) = @_;

   if ($cmd eq "open-filebrowser:open") {
      $self->openbrowser;
   }else{

   if ($cmd eq "open-filebrowser:openimageviewer") {
      $self->openimageviewer;
   }
   }

   ()
}

sub on_action {
   my ($self, $action) = @_;

   $action eq "open"
      and $self->openbrowser;

   ()
}

